### ISSUE TITLE
Setting LOGZIO_ZONE=eu Causes Errors

### ISSUE THREAD

**Issue by jimjkelly** [logzio/logzio-docker#11]
The following errors occur when trying to use the EU instead of US zone:

> logz_1           | logzio-logger error: Error: There was a problem with the request.
> logz_1           | Response: 401: Logging token is not valid Error: There was a problem with the request.
> logz_1           | Response: 401: Logging token is not valid
> logz_1           |     at Request._callback (/usr/src/app/node_modules/logzio-nodejs/lib/logzio-nodejs.js:253:30)
> logz_1           |     at Request.self.callback (/usr/src/app/node_modules/request/request.js:187:22)
> logz_1           |     at emitTwo (events.js:106:13)
> logz_1           |     at Request.emit (events.js:192:7)
> logz_1           |     at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1048:10)
> logz_1           |     at emitOne (events.js:96:13)
> logz_1           |     at Request.emit (events.js:189:7)
> logz_1           |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:969:12)
> logz_1           |     at emitNone (events.js:91:20)
> logz_1           |     at IncomingMessage.emit (events.js:186:7)

**Comment by nasis** [comment]
Hi Jim,
this seems like a configuration issue. Can you please contact us through support@logz.io?

**Comment by nasis** [comment]
Issue moved to support
