### ISSUE TITLE
Docker Hub does not reflect github

### ISSUE THREAD

**Issue by simon-chettle** [logzio/logzio-docker#18]
It would be nice if the latest tag on https://hub.docker.com/r/logzio/logzio-docker/tags/ reflected master.

**Comment by Mortinke** [comment]
I ran in the same issue and wonder why there is no feedback on such an old issue. Do you have an plans to update the docker image on docker hub?

**Comment by idohalevi** [comment]
@Mortinke @simon-chettle updated :)
