### ISSUE TITLE
No versioning exists for docker image

### ISSUE THREAD

**Issue by ddelnano** [logzio/logzio-docker#3]
I am using this docker image on my prod servers and I would prefer to not have to use latest since I see the docker image has been recently updated since I have started using it.  When spinning up new hosts (like I did today), I got the more recent version which is unwanted.  Is there any plan to version this??

**Comment by roiravhon** [comment]
Hey @ddelnano, 
We will address that issue as well with #4 .

Thanks!

**Comment by ranch78** [comment]
Addressed - now each new version will include version number as well
