### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by ddelnano** [logzio/logzio-docker#4]
I apologize in advance for this incredibly long post.

Using this docker image for integrating with your platform was awesome and so quick to get setup.  Unfortunately since we have been running this for the past week or so we started to run into problems.  The docker image causes high CPU and memory usage on our hosts and for our applications that receive 10-20k requests per minute we had our CPU and memory balloon to the point where we had to stop using this image.  I really like this solution and think its elegant so I spent some time profiling the application to see if I could find the root cause of the problems.

Below you will find the logs from this container and a screen shot of one of our server's CPU and memory after removing this logging container from our server

<img width="663" alt="screen shot 2016-10-13 at 8 31 08 am" src="https://cloud.githubusercontent.com/assets/5855593/19349147/903b5834-911f-11e6-9550-a170306ab81a.png">

From the picture above it is very obvious when we stopped using this container: CPU usage dipped from ~27% to ~2%

```
10/7/2016 7:09:30 PM  code: 'EAI_AGAIN',
10/7/2016 7:09:30 PM  errno: 'EAI_AGAIN',
10/7/2016 7:09:30 PM  syscall: 'getaddrinfo',
10/7/2016 7:09:30 PM  hostname: 'listener.logz.io',
10/7/2016 7:09:30 PM  host: 'listener.logz.io',
10/7/2016 7:09:30 PM  port: '8071' }
10/7/2016 7:10:01 PMlogzio-logger error: Error: getaddrinfo EAI_AGAIN listener.logz.io:8071 { [Error: getaddrinfo EAI_AGAIN listener.logz.io:8071]
10/7/2016 7:10:01 PM  code: 'EAI_AGAIN',
10/7/2016 7:10:01 PM  errno: 'EAI_AGAIN',
10/7/2016 7:10:01 PM  syscall: 'getaddrinfo',
10/7/2016 7:10:01 PM  hostname: 'listener.logz.io',
10/7/2016 7:10:01 PM  host: 'listener.logz.io',
10/7/2016 7:10:01 PM  port: '8071' }
10/7/2016 7:10:02 PMlogzio-logger error: Error: getaddrinfo EAI_AGAIN listener.logz.io:8071 { [Error: getaddrinfo EAI_AGAIN listener.logz.io:8071]
10/7/2016 7:10:02 PM  code: 'EAI_AGAIN',
10/7/2016 7:10:02 PM  errno: 'EAI_AGAIN',
10/7/2016 7:10:02 PM  syscall: 'getaddrinfo',
10/7/2016 7:10:02 PM  hostname: 'listener.logz.io',
10/7/2016 7:10:02 PM  host: 'listener.logz.io',
10/7/2016 7:10:02 PM  port: '8071' }
10/7/2016 7:10:34 PMlogzio-logger error: Error: getaddrinfo EAI_AGAIN listener.logz.io:8071 { [Error: getaddrinfo EAI_AGAIN listener.logz.io:8071]
10/7/2016 7:10:34 PM  code: 'EAI_AGAIN',
10/7/2016 7:10:34 PM  errno: 'EAI_AGAIN',
10/7/2016 7:10:34 PM  syscall: 'getaddrinfo',
10/7/2016 7:10:34 PM  hostname: 'listener.logz.io',
10/7/2016 7:10:34 PM  host: 'listener.logz.io',
10/7/2016 7:10:34 PM  port: '8071' }
10/7/2016 7:11:09 PMlogzio-logger error: Error: getaddrinfo EAI_AGAIN listener.logz.io:8071 { [Error: getaddrinfo EAI_AGAIN listener.logz.io:8071]
10/7/2016 7:11:09 PM  code: 'EAI_AGAIN',
10/7/2016 7:11:09 PM  errno: 'EAI_AGAIN',
10/7/2016 7:11:09 PM  syscall: 'getaddrinfo',
10/7/2016 7:11:09 PM  hostname: 'listener.logz.io',
10/7/2016 7:11:09 PM  host: 'listener.logz.io',
10/7/2016 7:11:09 PM  port: '8071' }
10/7/2016 7:11:57 PMlogzio-logger error: Error: getaddrinfo EAI_AGAIN listener.logz.io:8071 { [Error: getaddrinfo EAI_AGAIN listener.logz.io:8071]
10/7/2016 7:11:57 PM  code: 'EAI_AGAIN',
10/7/2016 7:11:57 PM  errno: 'EAI_AGAIN',
10/7/2016 7:11:57 PM  syscall: 'getaddrinfo',
10/7/2016 7:11:57 PM  hostname: 'listener.logz.io',
10/7/2016 7:11:57 PM  host: 'listener.logz.io',
10/7/2016 7:11:57 PM  port: '8071' }
10/7/2016 7:12:02 PMlogzio-logger error: Error: getaddrinfo EAI_AGAIN listener.logz.io:8071 { [Error: getaddrinfo EAI_AGAIN listener.logz.io:8071]
10/7/2016 7:12:02 PM  code: 'EAI_AGAIN',
10/7/2016 7:12:02 PM  errno: 'EAI_AGAIN',
10/7/2016 7:12:02 PM  syscall: 'getaddrinfo',
10/7/2016 7:12:02 PM  hostname: 'listener.logz.io',
10/7/2016 7:12:02 PM  host: 'listener.logz.io',
10/7/2016 7:12:02 PM  port: '8071' }
10/7/2016 7:12:22 PMlogzio-logger error: Error: getaddrinfo EAI_AGAIN listener.logz.io:8071 { [Error: getaddrinfo EAI_AGAIN listener.logz.io:8071]
10/7/2016 7:12:22 PM  code: 'EAI_AGAIN',
10/7/2016 7:12:22 PM  errno: 'EAI_AGAIN',
10/7/2016 7:12:22 PM  syscall: 'getaddrinfo',
10/7/2016 7:12:22 PM  hostname: 'listener.logz.io',
10/7/2016 7:12:22 PM  host: 'listener.logz.io',
10/7/2016 7:12:22 PM  port: '8071' }
10/7/2016 7:34:11 PMlogzio-logger error: Error: getaddrinfo EAI_AGAIN listener.logz.io:8071 { [Error: getaddrinfo EAI_AGAIN listener.logz.io:8071]
10/7/2016 7:34:11 PM  code: 'EAI_AGAIN',
10/7/2016 7:34:11 PM  errno: 'EAI_AGAIN',
10/7/2016 7:34:11 PM  syscall: 'getaddrinfo',
10/7/2016 7:34:11 PM  hostname: 'listener.logz.io',
10/7/2016 7:34:11 PM  host: 'listener.logz.io',
10/7/2016 7:34:11 PM  port: '8071' }
10/7/2016 7:34:11 PMlogzio-logger error: Error: getaddrinfo EAI_AGAIN listener.logz.io:8071 { [Error: getaddrinfo EAI_AGAIN listener.logz.io:8071]
10/7/2016 7:34:11 PM  code: 'EAI_AGAIN',
10/7/2016 7:34:11 PM  errno: 'EAI_AGAIN',
10/7/2016 7:34:11 PM  syscall: 'getaddrinfo',
10/7/2016 7:34:11 PM  hostname: 'listener.logz.io',
10/7/2016 7:34:11 PM  host: 'listener.logz.io',
10/7/2016 7:34:11 PM  port: '8071' }
10/7/2016 7:37:59 PMlogzio-logger error: Error: getaddrinfo EAI_AGAIN listener.logz.io:8071 { [Error: getaddrinfo EAI_AGAIN listener.logz.io:8071]
10/7/2016 7:37:59 PM  code: 'EAI_AGAIN',
10/7/2016 7:37:59 PM  errno: 'EAI_AGAIN',
10/7/2016 7:37:59 PM  syscall: 'getaddrinfo',
10/7/2016 7:37:59 PM  hostname: 'listener.logz.io',
10/7/2016 7:37:59 PM  host: 'listener.logz.io',
10/7/2016 7:37:59 PM  port: '8071' }
10/7/2016 7:38:02 PMlogzio-logger error: Error: getaddrinfo EAI_AGAIN listener.logz.io:8071 { [Error: getaddrinfo EAI_AGAIN listener.logz.io:8071]
10/7/2016 7:38:02 PM  code: 'EAI_AGAIN',
10/7/2016 7:38:02 PM  errno: 'EAI_AGAIN',
10/7/2016 7:38:02 PM  syscall: 'getaddrinfo',
10/7/2016 7:38:02 PM  hostname: 'listener.logz.io',
10/7/2016 7:38:02 PM  host: 'listener.logz.io',
10/7/2016 7:38:02 PM  port: '8071' }
10/8/2016 6:04:38 PM
10/8/2016 6:04:38 PM<--- Last few GCs --->
10/8/2016 6:04:38 PM
10/8/2016 6:04:38 PM128942085 ms: Scavenge 1398.2 (1458.1) -> 1398.2 (1458.1) MB, 2.3 / 0 ms (+ 3.6 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
10/8/2016 6:04:38 PM128944891 ms: Mark-sweep 1398.2 (1458.1) -> 1396.1 (1458.1) MB, 2806.2 / 0 ms (+ 5.3 ms in 2 steps since start of marking, biggest step 3.6 ms) [last resort gc].
10/8/2016 6:04:38 PM128947627 ms: Mark-sweep 1396.1 (1458.1) -> 1397.2 (1458.1) MB, 2735.7 / 0 ms [last resort gc].
10/8/2016 6:04:38 PM
10/8/2016 6:04:38 PM
10/8/2016 6:04:38 PM<--- JS stacktrace --->
10/8/2016 6:04:38 PM
10/8/2016 6:04:38 PM==== JS stack trace =========================================
10/8/2016 6:04:38 PM
10/8/2016 6:04:38 PMSecurity context: 0x38d5a1d81b1 <JS Object>
10/8/2016 6:04:38 PM    1: DefineObjectProperty [native v8natives.js:596] [pc=0x32485f23e926] (this=0x38d5a1f15a9 <JS Global Object>,K=0x72f21ff861 <a TCP with map 0x36c7fb717a29>,W=0x3c206fa0e179 <String[7]: reading>,H=0x72f21fe721 <a PropertyDescriptor with map 0x36c7fb717ce9>,Z=0x38d5a104231 <true>)
10/8/2016 6:04:38 PM    2: DefineOwnProperty(aka DefineOwnProperty) [native v8natives.js:~633] [pc=0x32485f7ae777] (this=0x38d5a104189...
10/8/2016 6:04:38 PM
10/8/2016 6:04:38 PMFATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

In addition to having problems taking to your servers, it is obvious that the node process runs out of memory and crashes.

So after having these issues and the dramatic CPU and memory usage I started to profile the application.  I have completed CPU profiling and below you will find my process and the results.  At first I attempted to profile this running the app as is inside the container but it proved more difficult than just running this application natively on my host so keep in mind this is not using the actual docker container.

Profiling Procedure 
- Spin up AWS t2.small from an AMI using Ubuntu 14.04, Docker 1.11
- Install Node 5.10.1 (same as the docker container) using the following commands
  - wget https://nodejs.org/download/release/v5.10.1/node-v5.10.1-linux-x64.tar.gz
  - tar -xvzf node-v5.10.1-linux-x64.tar.gz
  - sudo mv node-v5.10.1-linux-x64/bin/node /bin/
- Install Linux perf_events
  - sudo apt-get update && sudo apt-get install -y linux-tools-common linux-tools-3.13.0-74-generic linux-cloud-tools-3.13.0-74-generic
- Run single nginx container using the following command, I used our container orchestration platform to run the container but it could be run with the following `docker run -p 80:80 -d nginx`
- Get the source code for this project and install dependecies
  - git clone https://github.com/logzio/logzio-docker/ && cd logzio-docker
  - /home/ubuntu/node-v5.10.1-linux-x64/bin/npm install
- Run this project with node profiling enabled
  - sudo node --perf-basic-prof-only-functions  index.js -t my-token -a env=testing --no-dockerEvents --no-stats
- Generate traffic to container by curling in a while loop running the process in the background
  - ./infinite-curl.sh > /dev/null 2>&1 & (I ran about 5 of these)
- Run perf_events while that is happening
  - sudo perf record -F 99 -p 15934 -g -- sleep 30
- Follow rest of steps at [this](https://github.com/brendangregg/FlameGraph) Github repo to obtain the following picture 

(Will post later since I need to convert them from svg format)

From my untrained eye (since I am new to this profiling stuff) it seems to me that there is alot of CPU time spent in garbage collection which makes sense since my logs show the process running out of memory.  Nothing is immediately obvious from looking at these pictures briefly but I will continue to look at them.  I plan on profiling the memory to check for memory leaks since the flamegraph and the logs make me think that the CPU usage is really caused from the memory usage and garbage collection.

Not sure if you guys have any experience with this but would love help on this since I really want this solution to work for us.

**Comment by ddelnano** [comment]
Here are the flamegraph pictures I promised.  They are not very useful as pngs since you can't zoom into them and look at each individual call stack but let me know and I can give you the original svgs.

![out4](https://cloud.githubusercontent.com/assets/5855593/19350260/08108032-9125-11e6-95cb-0b05b31edd0f.png)
![out5](https://cloud.githubusercontent.com/assets/5855593/19350261/081620a0-9125-11e6-964b-4130a2a68c1d.png)

**Comment by roiravhon** [comment]
Thanks for that @ddelnano!

We really appreciate this detailed issue.
We are assigning someone on that, we will keep you update on progress.

Thanks again,
Roi.

**Comment by ddelnano** [comment]
Thanks for the quick response and its awesome you guys will look into this.

As I said I plan to have some memory profiling as well, but if there is anything I can help with don't hesitate to ask.

**Comment by ddelnano** [comment]
Just wanted to post an update of additional error messages I saw in the logs recently.  Seems to be server errors.

<img width="691" alt="screen shot 2016-10-17 at 9 44 38 am" src="https://cloud.githubusercontent.com/assets/5855593/19440056/6f629104-944e-11e6-8b1a-850932327983.png">

**Comment by gillyb** [comment]
Hey @ddelnano - First of all, amazing work on profiling the processes and looking into this. I am investigating this issue, but might take me some time.. 

From first look at the flame graphs you sent though, I actually don't see a lot of time being spent on Garbage Collection, but I'll look further into it.
Thanks a lot, and I'll keep you updated with my progress.

**Comment by ddelnano** [comment]
@gillyb yea after taking another look you are right.  But thanks for looking into this. @ranch78 updated a new version and I plan on profiling that soon.

As for the nginx errors I saw in my logs, do you guys have any idea why that is happening?

**Comment by gillyb** [comment]
@ddelnano Cool, I'm waiting to see how the newer version performs for you. I'm still planning on profiling the shipper and improving it a bit, and I'll keep you updated with that.
Regarding the nginx errors, we're looking into that too...

**Comment by ddelnano** [comment]
@gillyb I should have some time tomorrow to try it out.

**Comment by ranch78** [comment]
A refactoring of the code was done to run the logger more efficient 
According to our tests Memory usage went drastically down (using version 2.0 and up)
