### ISSUE TITLE
Improve the Dockerfile

### ISSUE THREAD

**Issue by Lawouach** [logzio/logzio-docker#5]
Hey there,

The current [Dockerfile](https://github.com/logzio/logzio-docker/blob/master/Dockerfile) is not optimal.

For instance, 

```
RUN npm install --production
RUN npm cache clean
```

The second `RUN` is useless here because the previous layer will always contain the cache anyway. You should write:

```
RUN npm install --production && npm cache clean
```

Here is a slight modified version (off the top of my head):

```
FROM mhart/alpine-node:5.10.1
MAINTAINER Ran Ramati <ran@logz.io>
RUN apk add --no-cache bash && rm -rf /var/cache/apk/*
RUN npm install --production && npm cache clean

WORKDIR /usr/src/app
COPY package.json package.json
COPY index.js index.js
ENTRYPOINT ["/usr/src/app/index.js"]
CMD []
```

Also, why do you even install `bash`? If it's not expected by your app, please don't install it at all. Just run `sh` which is already installed.

**Comment by ranch78** [comment]
We have applied some changes as suggested to the dockerfile 
Thanks
