### ISSUE TITLE
Your docker solution vs the logentries one

### ISSUE THREAD

**Issue by Lawouach** [logzio/logzio-docker#6]
Hi there,

Going through your docker image, I was surprised how similar it looked to the logentries one.

https://github.com/rapid7/docker-logentries

Did you guys draw inspiration from their work?

**Comment by ranch78** [comment]
They are both based on the same node.js packages 
https://github.com/mcollina/docker-loghose and 
https://github.com/mcollina/docker-allcontainers
As you can see it is a reuse of the packages code
