### ISSUE TITLE
Not all parameters configured via environ vars

### ISSUE THREAD

**Issue by saabeilin** [logzio/logzio-docker#9]
Adjusting configuration via the environment variables is much more convenient with multi-host deploys and especially with Docker Swarm mode. Would be nice to have full control via env vars the same way as the command-line parameters now.

**Comment by segalziv** [comment]
Hi @saabeilin, that indeed sounds reasonable. We'll try to add env vars as soon as we can. Will update here.

**Comment by xavijs** [comment]
+1

**Comment by simon-chettle** [comment]
+1

**Comment by guy93r** [comment]
Hi @saabeilin (and everyone else in this issuse)! 
Just updated the code. Just rebuild the docker image and you should be able to configure docker via environment variables.
